sentry:
  dsn: "%env(resolve:SENTRY_DSN)%"
  options:
    environment: "%env(resolve:APP_ENV)%"
    ignore_exceptions:
      - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
      - Symfony\Component\Security\Core\Exception\AccessDeniedException
