<?php

namespace App\Repository;

use App\Entity\Author;
use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{

    public function findOrCreate($id, $name) {

        if ($id !== null) {
            $author = $this->find($id);
            if ($author !== null) {
                return $author;
            }
        }

        if ($name !== null) {
            $author = $this->createQueryBuilder('a')
                ->where("LOWER(a.name) LIKE :query")
                ->setParameter('query', mb_strtolower($name))
                ->getQuery()
                ->setMaxResults(1)
                ->getSingleResult();

            if ($author !== null) {
                return $author;
            }
        }

        $author = new Author();
        $author->setName($name);

        return $author;
    }
    public function search($term) {
        $query = $this->createQueryBuilder("a");

        $query
            ->where("LOWER(a.name) LIKE :query")
            ->setParameter("query", "%" . mb_strtolower($term) . "%");

        return $query
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }
}
